export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const FETCH_LOCKERS = 'FETCH_LOCKERS';
export const FETCH_LOCKERS_ERROR = 'FETCH_LOCKERS_ERROR';

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_ERROR = 'FETCH_ADDRESSES_ERROR';